version: '3.9'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: zipteste
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DB_NAME: zipteste
      DB_USER: admin
      DB_PASSWORD: admin
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data: